### ISSUE TITLE
Restaurant owner registration

### ISSUE THREAD

**Issue by MarkusPaulsen** [MarkusPaulsen/TheSpoon#19]
**Role:**
Restaurant owner

**Feature:**
Register as an owner

**Reason:**
Log in to the system

**Description:**
Realise the registration function for a restaurant owner

**Acceptance criteria:**
 - [x] Restaurant owner select whether he/she is actually a restaurant owner
 - [x] Restaurant owner can enter his/her user name (unique)
 - [x] Restaurant owner can enter his/her first name
 - [x] Restaurant owner can enter his/her surname
 - [x] Restaurant owner can enter his/her e-mail address
 - [x] Restaurant owner can enter his/her password
 - [x] Restaurant owner has to confirm his/her password
 - [x] Restaurant owner's input is validated
 - [x] Restaurant owner can click on confirm to finish the registration process in case the input is valid
 - [x] Restaurant owner is continued to the “restaurant setup page” after he/she finished the registration process and the backend confirms the registration

**Priority:** 1
**Value:** 5

**Comment by Andresayan** [comment]
TODO:
- Use better fields for some information (SignUp.js)
- Handle the submission with the buttons
- Handle changes in fields
- State management for data
- Link with Backend to store data
- Implement React Bootstrap for better UI

**Comment by zulicek** [comment]
DONE:
- added React Bootstrap, regular bootstrap and scss modules
- created Signup component with proceeding to customer and restaurant owner registration
- implemented styles according to the design

TODO:
- login component
- enable switching between login and signup component ("Already (Don't) have an account" text)
- handle the submission with the buttons
- validation
- state management for data
- link with Backend to store data

CHANGE IF NEEDED:
- if customer and restaurant owners don't have the same data Register component should be changed (according to the design, restaurant owner doesn't have nationality and birthday fields)

**Comment by zulicek** [comment]
DONE: 
- add icon left arrow to go back to choosing roles
- add font size for buttons (15px, but 18px on homepage)
- add background image
- add logo

TODO:
- login component
- enable switching between login and signup component ("Already (Don't) have an account" text)
- handle the submission with the buttons
- validation
- state management for data
- link with Backend to store data

CHANGE IF NEEDED:
- if customer and restaurant owners don't have the same data Register component should be changed (according to the design, restaurant owner doesn't have nationality and birthday fields)

STYLING CHANGES:
- style nationality input
