### ISSUE TITLE
Customer registration 

### ISSUE THREAD

**Issue by MarkusPaulsen** [MarkusPaulsen/TheSpoon#44]
**Role:**
Customer

**Feature:**
Register as a customer

**Reason:**
Log in to the system / app

**Description:**
Realise the registration function for a customer

**Acceptance criteria:**
 - [x] Customer select whether he/she is actually a customer
 - [x] Customer can enter his/her user name (unique)
 - [x] Customer can enter his/her first name (optional)
 - [x] Customer can enter his/her surname (optional)
 - [x] Customer can enter his/her e-mail address
 - [x] Customer can enter his/her password
 - [x] Customer has to confirm his/her password
 - [x] Customer's input is validated
 - [x] Customer can click on confirm to finish the registration process in case the input is valid
 - [x] Customer gets redirected to the web page when trying to log in to the app without having registered first
 - [x] Customer is logged into TheSpoon after he/she finished the registration process and the backend confirms the registration

**Priority:** 1
**Value:** 5

**Comment by zulicek** [comment]
WEB DONE:
- Customer select whether he/she is actually a customer
- Customer can enter his/her name
- Customer can enter his/her surname
- Customer can enter his/her e-mail address
- Customer can enter his/her password
- Customer has to confirm his/her password

**Comment by hjstang** [comment]
@zulicek Can I move this issue to closed?
