### ISSUE TITLE
Customer change name

### ISSUE THREAD

**Issue by MarkusPaulsen** [MarkusPaulsen/TheSpoon#46]
**Role:**
Customer

**Feature:**
Change my name

**Reason:**
Update my name to my current needs

**Description:**
Realise updating the name of the customer

**Acceptance criteria:**
 - [ ] Customer can enter his/her new name
 - [ ] Customer can enter his/her new surname
 - [ ] Customer's input is validated
 - [ ] Customer can click on update to perform the update of the name and the surname in case the input is valid
 - [ ] New name and surname are shown in the profile in case the backend confirms the change

**Priority:** 2
**Value:** 1

**Comment by cathrbak** [comment]
This is not relevant anymore. Closing the issue
