### ISSUE TITLE
Customer search

### ISSUE THREAD

**Issue by MarkusPaulsen** [MarkusPaulsen/TheSpoon#51]
**Role:**
Customer

**Feature:**
Search for specific dishes/drink

**Reason:**
fulfill my desire of the day

**Description:**
Realise search function for dishes and drinks

**Acceptance criteria:**
 - [x] Customer can enter search term in a search bar
 - [x] Customer's input is validated
 - [x] Customer can finalise search with search button in case the input is valid
 - [x] Search results are shown after he/she finalise the search process and the backend delivers the results

**Priority:** 1
**Value:** 5

**Comment by hjstang** [comment]
@MarkusPaulsen what is meant by the acceptance criteria "customer's input is validated"? What kind of validation do we need?

**Comment by cathrbak** [comment]
Remaining: 
 - [ ] Handle tags properly

**Comment by cathrbak** [comment]
Finished in branch mobile/tags, PR coming today
