### ISSUE TITLE
Customer change user name

### ISSUE THREAD

**Issue by MarkusPaulsen** [MarkusPaulsen/TheSpoon#81]
**Role:**
Customer

**Feature:**
Change my user name

**Reason:**
Update my user name to my current needs

**Description:**
Realise updating the user name of the customer

**Acceptance criteria:**
 - [ ] Customer can enter his/her new user name
 - [ ] Customer's input is validated
 - [ ] Customer can click on update to perform the update of the user name
 - [ ] New user name is shown in the profile in case the backend confirms the change
 - [ ] Customer can only log in with the new user name

**Priority:** 2
**Value:** 1

**Comment by cathrbak** [comment]
This should not be possible? It is not normal to be able to change a user name

**Comment by cathrbak** [comment]
It should not be possible. Closing this issue
